<center><h1>**تعلم لغة بايثون**</h1></center>

In [2]:
# numpy جلب مكتبة نامباي  
import numpy as np

The NumPy library is the core library for scientific computing in
Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays. 

# انشاء مجموعة من المصفوفة مختلفة الأبعاد

In [7]:
a = np.array([1,2,3])

print('a: ', a) 

a:  [1 2 3]


In [12]:
# this “array” is interchangeably called “matrix” or also “vector”. 
# Matrix shape is 2 X 3”. 

b = np.array([(1.5,2,3), (4,5,6)], dtype = float)

b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [10]:
c = np.array([[(1.5,2,3), (4,5,6)], 
              [(3,2,1), (4,5,6)]],dtype = float)

c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### zeros

In [11]:
# np.zeros((n,m)) returns an n x m matrix that contains zeros.
# إنشاء مجموعة/مصفوفة من الأصفار
np.zeros((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### ones

In [12]:
# إنشاء صفيف من الاحاد
np.ones((2,3,4),dtype=np.int16) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
# إنشاء صفيف من القيم المتساوية التباعد
# syntax : arange((start, end, step))
d = np.arange((0,45,5)) # step value - قيمة الخطوة
d

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40])

In [17]:
# إنشاء صفيف من القيم المتساوية التباعد
np.linspace(0,2,9)  # number of samples - تعداد القيم

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [4]:
# إنشاء صفيف ثنائي الأبعاد مملوء بالعدد 7
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [ ]:
# انشاء مصفوفة 
np.eye(2) # Create a 2X2 identity matrix

In [21]:
# انشاء صفيف من القيم العشوائية 
np.random.random((4,5)) # Create an array with random values

array([[0.54907207, 0.95383388, 0.87490586, 0.6709496 , 0.89377964],
       [0.08599191, 0.43716102, 0.77928411, 0.99180759, 0.07255981],
       [0.07291244, 0.7826684 , 0.88580152, 0.85249698, 0.39008228],
       [0.39660932, 0.59419057, 0.22627556, 0.40064196, 0.59121004]])

In [18]:
np.empty((3,2)) 

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

<h2> inspecting array - صفيف </h2>

In [23]:
print(a.shape) # Array dimensions - بعد الصفيف

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(len(a)) # Length of array - طول الصفيف

In [ ]:
print(b.ndim) #Number of array dimensions - قيمة بعد الصفيف

In [ ]:
print(e.size) #Number of array elements - عدد القيم داخل الصفيف

In [ ]:
print(b.dtype) #Data type of array elements - نوع عناصر الصفيف

In [ ]:
print(b.dtype.name) #Name of data type - 
b.astype(int) 

### Reshape

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9] )
arr
arr.reshape(3,3)

# <center style='color:blue'> math functions </center>

### np.sum

In [37]:
A = np.array([1,2,3,4,5,6]) # array
M = A.reshape(2,3) # matrix
print('A = ',A)
print('M = ')
print(M)

A =  [1 2 3 4 5 6]
M = 
[[1 2 3]
 [4 5 6]]


In [38]:
# np.sum() adds all the elements of the matrix.
A.sum() # Array-wise sum

21

In [39]:
M.sum()

21

### np.cumsum

In [41]:
A.cumsum(axis=0) # Cumulative sum of the elements


array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [42]:
M.cumsum(axis=0) # Cumulative sum of the elements


array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [43]:
M.cumsum(axis=1) # Cumulative sum of the elements


array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [13]:
a.min() # Array-wise minimum value

1

In [ ]:
b.max(axis=0) # Maximum value of an array row

In [ ]:
a.mean() # Mean

In [ ]:
b.median() # Median


In [ ]:
np.std(b) # standard deviation

In [ ]:
a.corrcoef() # Correlation coefficient


### matrix multiplication

In [32]:
# generate an identity matrix of (3 x 3)
I = np.eye(3)
print('I: ')
print(I)

# generate another (3 x 3) matrix to be multiplied.
D = np.arange(1,10).reshape(3,3)

print('D: ')
print(D)


I: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
D: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
# perform actual dot product.
M = np.dot(D,I)
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

Python Lists vs. Numpy Arrays - What is the difference?

np arrays are better interms of faster computation and ease of manipulation.

In [14]:
# python array
lst = [1,2,3,4,5,6,7,8,9]
# numpy array
arr = np.array([1,2,3,4,5,6,7,8,9])

print('lst: ',lst)
print('arr: ',arr)

lst:  [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr:  [1 2 3 4 5 6 7 8 9]


arange([start],stop,[step])

the stopping number is not going to be included in the list.

In [15]:
import time 
size_of_vec = 1000000

def python_list():
    t = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t

def numpy_array():
    t = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t

print('list perf: ')
t1 = python_list()
print(t1)

print('numpy perf: ')
t2 = numpy_array()
print(t2)

print("Numpy is in this example " + str(t1/t2) + " faster!")

list perf: 
0.4557371139526367
numpy perf: 
0.007996797561645508
Numpy is in this example 56.98995259533109 faster!


In [ ]:
### قراءة ملف
np.loadtxt("myfile.txt")
np.genfromtxt("my_file.csv", delimiter=',')
np.savetxt("myarray.txt", a, delimiter=" ")