<center><h1>**تعلم لغة بايثون**</h1></center>

In [2]:
# numpy جلب مكتبة نامباي  
import numpy as np

The NumPy library is the core library for scientific computing in
Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays. 

In [10]:
# انشاء مجموعة من المصفوفة مختلفة الأبعاد
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)

print('a: ', a, '\n') 

print('b: ')
print(b, '\n')

print('c: ')
print(c)

a:  [1 2 3] 

b: 
[[1.5 2.  3. ]
 [4.  5.  6. ]]
c: 
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [11]:
# إنشاء مجموعة/مصفوفة من الأصفار
np.zeros((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# إنشاء صفيف من الاحاد
np.ones((2,3,4),dtype=np.int16) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
# إنشاء صفيف من القيم المتساوية التباعد
d = np.arange(0,45,5) ) # step value - قيمة الخطوة
d

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40])

In [17]:
# إنشاء صفيف من القيم المتساوية التباعد
np.linspace(0,2,9) ) # number of samples - تعداد القيم

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [4]:
# إنشاء صفيف ثنائي الأبعاد مملوء بالعدد 7
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [ ]:
# انشاء مصفوفة 
np.eye(2) ) # Create a 2X2 identity matrix

In [21]:
# انشاء صفيف من القيم العشوائية 
np.random.random((4,5)) # Create an array with random values

array([[0.54907207, 0.95383388, 0.87490586, 0.6709496 , 0.89377964],
       [0.08599191, 0.43716102, 0.77928411, 0.99180759, 0.07255981],
       [0.07291244, 0.7826684 , 0.88580152, 0.85249698, 0.39008228],
       [0.39660932, 0.59419057, 0.22627556, 0.40064196, 0.59121004]])

In [18]:
np.empty((3,2)) 

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

) #) #) # قراءة ملف

In [ ]:
np.loadtxt("myfile.txt")
np.genfromtxt("my_file.csv", delimiter=',')
np.savetxt("myarray.txt", a, delimiter=" ")

<h2> inspecting array - صفيف </h2>

In [23]:
print(a.shape) # Array dimensions - بعد الصفيف
print(len(a)) # Length of array - طول الصفيف
print(b.ndim) #Number of array dimensions - قيمة بعد الصفيف
print(e.size) #Number of array elements - عدد القيم داخل الصفيف
print(b.dtype) #Data type of array elements - نوع عناصر الصفيف
print(b.dtype.name) #Name of data type - 
b.astype(int) 

array([[1, 2, 3],
       [4, 5, 6]])

aggregates

In [ ]:
a.sum() Array-wise sum
a.min() Array-wise minimum value
b.max(axis=0) Maximum value of an array row
b.cumsum(axis=1) Cumulative sum of the elements
a.mean() Mean
b.median() Median
np.std(b)

In [ ]:
a.corrcoef() Correlation coefficient
