<center><h1>**تعلم لغة بايثون**</h1></center>

In [2]:
# numpy جلب مكتبة نامباي  
import numpy as np

The NumPy library is the core library for scientific computing in
Python. It provides a high-performance multidimensional array
object, and tools for working with these arrays. 

# انشاء مجموعة من المصفوفة مختلفة الأبعاد

In [7]:
a = np.array([1,2,3])

print('a: ', a) 

a:  [1 2 3]


In [12]:
# this “array” is interchangeably called “matrix” or also “vector”. 
# Matrix shape is 2 X 3”. 

b = np.array([(1.5,2,3), (4,5,6)], dtype = float)

b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [10]:
c = np.array([[(1.5,2,3), (4,5,6)], 
              [(3,2,1), (4,5,6)]],dtype = float)

c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### zeros

In [11]:
# np.zeros((n,m)) returns an n x m matrix that contains zeros.
# إنشاء مجموعة/مصفوفة من الأصفار
np.zeros((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### ones

In [12]:
# إنشاء صفيف من الاحاد
np.ones((2,3,4),dtype=np.int16) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [16]:
# إنشاء صفيف من القيم المتساوية التباعد
# syntax : arange((start, end, step))
d = np.arange((0,45,5)) # step value - قيمة الخطوة
d

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40])

In [17]:
# إنشاء صفيف من القيم المتساوية التباعد
np.linspace(0,2,9)  # number of samples - تعداد القيم

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [4]:
# إنشاء صفيف ثنائي الأبعاد مملوء بالعدد 7
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [ ]:
# انشاء مصفوفة 
np.eye(2) # Create a 2X2 identity matrix

In [21]:
# انشاء صفيف من القيم العشوائية 
np.random.random((4,5)) # Create an array with random values

array([[0.54907207, 0.95383388, 0.87490586, 0.6709496 , 0.89377964],
       [0.08599191, 0.43716102, 0.77928411, 0.99180759, 0.07255981],
       [0.07291244, 0.7826684 , 0.88580152, 0.85249698, 0.39008228],
       [0.39660932, 0.59419057, 0.22627556, 0.40064196, 0.59121004]])

In [18]:
np.empty((3,2)) 

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

<h2> inspecting array - صفيف </h2>

In [23]:
print(a.shape) # Array dimensions - بعد الصفيف

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(len(a)) # Length of array - طول الصفيف

In [ ]:
print(b.ndim) #Number of array dimensions - قيمة بعد الصفيف

In [ ]:
print(e.size) #Number of array elements - عدد القيم داخل الصفيف

In [ ]:
print(b.dtype) #Data type of array elements - نوع عناصر الصفيف

In [ ]:
print(b.dtype.name) #Name of data type - 
b.astype(int) 

### Reshape

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9] )
arr
arr.reshape(3,3)

# <center style='color:blue'> math functions </center>

### np.sum

In [37]:
A = np.array([1,2,3,4,5,6]) # array
M = A.reshape(2,3) # matrix
print('A = ',A)
print('M = ')
print(M)

A =  [1 2 3 4 5 6]
M = 
[[1 2 3]
 [4 5 6]]


In [38]:
# np.sum() adds all the elements of the matrix.
A.sum() # Array-wise sum

21

In [39]:
M.sum()

21

In [46]:
# sum allong rows
np.sum(M,axis=1)

array([ 6, 15])

In [48]:
# sum allong columns
np.sum(M,axis=0)

array([5, 7, 9])

### np.cumsum

In [41]:
A.cumsum(axis=0) # Cumulative sum of the elements


array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [42]:
M.cumsum(axis=0) # Cumulative sum of the elements


array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [43]:
M.cumsum(axis=1) # Cumulative sum of the elements


array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

### min, max 

In [44]:
A.min() # Array-wise minimum value

1

In [ ]:
b.max(axis=0) # Maximum value of an array row

### mean, median, std

In [ ]:
a.mean() # Mean

In [ ]:
b.median() # Median


In [ ]:
np.std(b) # standard deviation

In [ ]:
a.corrcoef() # Correlation coefficient


# <center style='color:blue'> matrix multiplication </center> 

In [59]:
A = np.arange(0,10).reshape(2,5)
B = np.arange(10,20).reshape(2,5)

In [62]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
B

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
np.add(A,B) # Addition


array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [64]:
# Subtraction
np.subtract(A,B) 


array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [65]:
# Division
np.divide(A,B) 


array([[0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429],
       [0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421]])

### matrix multiplication 

In [32]:
# generate an identity matrix of (3 x 3)
I = np.eye(3)
print('I: ')
print(I)

# generate another (3 x 3) matrix to be multiplied.
D = np.arange(1,10).reshape(3,3)

print('D: ')
print(D)


I: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
D: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
# perform actual dot product.
M = np.dot(D,I)
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
# A @ B Multiplication operator
np.multiply(B,A) # Multiplication
np.dot(A,B) # dot product
npf.vdot(A,B) # Vector dot product


# <center style='color:blue'> Python Lists vs. Numpy Arrays - What is the difference? </center> 

np arrays are better interms of faster computation and ease of manipulation.

In [14]:
# python array
lst = [1,2,3,4,5,6,7,8,9]
# numpy array
arr = np.array([1,2,3,4,5,6,7,8,9])

print('lst: ',lst)
print('arr: ',arr)

lst:  [1, 2, 3, 4, 5, 6, 7, 8, 9]
arr:  [1 2 3 4 5 6 7 8 9]


arange([start],stop,[step])

the stopping number is not going to be included in the list.

In [15]:
import time 
size_of_vec = 1000000

def python_list():
    t = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t

def numpy_array():
    t = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t

print('list perf: ')
t1 = python_list()
print(t1)

print('numpy perf: ')
t2 = numpy_array()
print(t2)

print("Numpy is in this example " + str(t1/t2) + " faster!")

list perf: 
0.4557371139526367
numpy perf: 
0.007996797561645508
Numpy is in this example 56.98995259533109 faster!


In [ ]:
### قراءة ملف
np.loadtxt("myfile.txt")
np.genfromtxt("my_file.csv", delimiter=',')
np.savetxt("myarray.txt", a, delimiter=" ")

# <center style='color:blue'> Broadcasting </center> 

In [ ]:
Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:


In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x



In [ ]:
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)
This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. We could implement this approach like this:

import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"
Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"
The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.



Broadcasting two arrays together follows these rules:

If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
The arrays can be broadcast together if they are compatible in all dimensions.
After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension
If this explanation does not make sense, try reading the explanation from the documentation or this explanation.

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the documentation.



Here are some applications of broadcasting:


In [ ]:

import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)