<center><h1>**تعلم لغة بايثون**</h1></center>

In [ ]:
# numpy جلب مكتبة نامباي  
import numpy as np # alias

The NumPy library is the core library for scientific computing in Python. مكتبة نامباي هي المكتبة الجوهرية في الحساب العلمي في بايثون

It provides a high-performance multidimensional array object توفر صفيف متعدد الابعاد ذو اداء عالي

and tools for working with these arrays. و الادوات للعمل بهذا الصفيف

# انشاء مجموعة/مصفوفة مختلفة الأبعاد

In [ ]:
a = np.array([1,2,3])
a

In [ ]:
print(a) 

In [ ]:
# this “array” is called a matrix or vector - صفيف او متجهة
# Matrix is of shape 2 X 3

b = np.array([(1,2,3), (4,5,6)], dtype = int)

b

In [ ]:
c = np.array([[(1.5,2,3), (4,5,6)], 
              [(3,2,1), (4,5,6)]],
             dtype = float)

c

### zeros

In [ ]:
# np.zeros((n,m)) returns an n x m matrix that contains zeros.
# إنشاء مجموعة/مصفوفة من الأصفار
np.zeros((3,4)) 

### ones

In [ ]:
# إنشاء صفيف من الاحاد
np.ones((2,3,4),dtype=np.int16) 

### arange

In [ ]:
# إنشاء صفيف من القيم المتساوية التباعد
# syntax : arange((start, end, step))
d = np.arange(0,45,5) # step value - قيمة الخطوة
d

### linspace

In [ ]:
# إنشاء صفيف من القيم المتساوية التباعد
np.linspace(0,2,9)  # number of samples - تعداد القيم

In [ ]:
# إنشاء صفيف ثنائي الأبعاد مملوء بالعدد 7
e = np.full((2,2),7)
e

In [ ]:
# انشاء مصفوفة الوحدة   
np.eye(2) # Create a 2X2 identity matrix

In [ ]:
# انشاء صفيف من القيم العشوائية 
np.random.random((4,5)) # Create an array with random values

In [ ]:
np.empty((3,2)) 

<h2> inspecting array - تفتيش صفيف  </h2>

In [ ]:
a = np.array([1,2,3])
a

In [ ]:
a.ndim # Array dimensions - بعد/درجة الصفيف

In [ ]:
print(a.shape) # شكل الصفيف

In [ ]:
print(a.size) #Number of array elements - عدد القيم داخل الصفيف

In [ ]:
b = np.array([(1,2,3), (4,5,6)], dtype = int)

b

In [ ]:
b.ndim

In [ ]:
print(b.shape) # شكل الصفيف

In [ ]:
print(b.size) #Number of array elements - عدد القيم داخل الصفيف

In [ ]:
print(b.dtype) #Data type of array elements - نوع عناصر الصفيف

### Reshape - تشكيل الصفيف

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9] )
arr
arr.reshape(3,3)

# <center style='color:blue'> math functions - وظائف/دوال رياضية </center>

### np.sum

In [ ]:
A = np.array([1,2,3,4,5,6]) # array
print('A = ',A)

In [ ]:
# np.sum() adds all the elements of the matrix.
A.sum() # Array-wise sum

In [ ]:
M = A.reshape(2,3) # matrix
print('M = ')
print(M)

In [ ]:
M.sum()

In [ ]:
# sum allong columns
np.sum(M,axis=0)

In [ ]:
# sum allong rows
np.sum(M,axis=1)

### np.cumsum : cumulative sum الجمع التراكمي

In [ ]:
A

In [ ]:
A.cumsum() # Cumulative sum of the elements

In [ ]:
M.cumsum(axis=0) # Cumulative sum of the elements


In [ ]:
M.cumsum(axis=1) # Cumulative sum of the elements


### min, max 

In [ ]:
A.min() # Array-wise minimum value

In [ ]:
M.max(axis=0) # Maximum value of an array row

### mean, median, std - المتوسط, الوسيط ,الانحراف المعياري

In [ ]:
a = np.array([1,2,3,5,8])
b = np.array([(1,2,3), (4,5,6)], dtype = int)


In [ ]:
a.mean() # Mean

In [ ]:
np.median(a) # Median

In [ ]:
np.std(a)

In [ ]:
b.mean() 


In [ ]:
np.median(b)

In [ ]:
np.std(b) # standard deviation

# <center style='color:blue'> matrix Operations</center> 

In [ ]:
A = np.arange(0,10).reshape(2,5)
B = np.arange(10,20).reshape(2,5)

In [ ]:
A

In [ ]:
B

### Addition

In [ ]:
np.add(A,B) # Addition


### Subtraction

In [ ]:
# 
np.subtract(A,B) 


### Division

In [ ]:

np.divide(A,B) 


# <center style='color:green'> matrix multiplication </center> 

### multilply

In [ ]:
# A @ B Multiplication operator
np.multiply(A,B)

### dot
to multiply two matrices A of dim (a1,a2) and B of dim (b1,b2) : 
* we need a2 = b1

In [ ]:
# generate an identity matrix of (3 x 3)
I = np.eye(3)
print('I: ')
print(I)

# generate another (3 x 3) matrix to be multiplied.
D = np.arange(1,10).reshape(3,3)

print('D: ')
print(D)


In [ ]:
# perform actual dot product.
M = np.dot(D,I)
M

--------------------- 

In [ ]:
A = np.arange(0,10).reshape(2,5)
B = np.arange(10,20).reshape(2,5)
print(A.shape)
print(A)
print(B.shape)
print(B)

In [ ]:
np.dot(A,B)

In [ ]:
B = np.arange(10,20).reshape(5,2)

In [ ]:
np.dot(A,B)

# <center style='color:blue'> Python Lists vs. Numpy Arrays </center> 

## <center> Why numpy ? لماذا نامباي </center> 

numpy arrays are better in terms of : نامباي مكبتة قوية في التحليل الرقمي
* faster computation   حساب اسرع
* ease of manipulation سهولة في معالجة البيانات 

In [84]:
import time 
vector_size = 1000000

def python_list():
    t = time.time()
    X = range(vector_size)
    Y = range(vector_size)
    Z = [X[i] + Y[i] for i in range(len(X)) ]
    return time.time() - t

def numpy_array():
    t = time.time()
    X = np.arange(vector_size)
    Y = np.arange(vector_size)
    Z = X + Y
    return time.time() - t


In [85]:
print('list perf: ')
t1 = python_list()
print(t1)

list perf: 
0.8558061122894287


In [86]:
print('numpy perf: ')
t2 = numpy_array()
print(t2)

numpy perf: 
0.012989521026611328


In [87]:
print("Numpy is in this example " + str(t1/t2) + " faster!")

Numpy is in this example 65.88434712382072 faster!


# <center style='color:blue'> Broadcasting </center> 

it is a mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. 

Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.



### adding a vector using a for loop

In [ ]:
# example : adding a constant vector to each row of a matrix

import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print('x = ')
print(x , '\n')
print('y = ')
print(y)

### alternative to loop (stacking + elementwise summation)

This works; however when the matrix x is very large, computing an explicit loop in Python could be slow. 
Note that adding the vector v to each row of the matrix x is equivalent to forming a matrix vv by stacking multiple copies of v vertically, then performing elementwise summation of x and vv. 

We could implement this approach like this:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y) 

### Broadcasting to the rescue

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:


In [ ]:

import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.


### Broadcasting two array - Rules

* If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.

* The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.

* The arrays can be broadcast together if they are compatible in all dimensions.

* After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.

* In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

* Functions that support broadcasting are known as universal functions. (check the doc)


### Applications of broadcasting:

### outer product of vectors

In [ ]:
### for me
# scalar 
np.array(1).shape # ()

# array 
np.array([1]).shape # (1,)

np.reshape(np.array([1]), (1,1)).shape # (1,1)

In [ ]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
print('v = ', v)
print('w = ', w)

In [ ]:
v.shape

In [ ]:
np.reshape(v, (3,1))

In [ ]:

# To compute an outer product, we first reshape v to be a column vector of shape (3, 1); 
# we can then broadcast it against w to yield an output of shape (3, 2), 
# which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

### dot product 

In [ ]:
np.reshape(w, (1,2))

In [ ]:
np.reshape(v,(3,1)).dot(np.reshape(w, (1,2)))

### add a vector to each row of a matrix

In [ ]:
x = np.array([[1,2,3], [4,5,6]])
print('shape: ',x.shape)
print('x = ',x)
print()
print('shape: ',w.shape)
print('v = ', v)

In [ ]:
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),

print(x + v)

### Add a vector to each column of a matrix


In [ ]:
print('shape: ',x.shape)
print('x = ',x)
print()
print('shape: ',w.shape)
print('w = ', w)

In [ ]:
x.T

In [ ]:
print(x.T )

In [ ]:
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)

In [ ]:

# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same output.
print(x + np.reshape(w, (2, 1)))



### Multiply a matrix by a constant:


In [ ]:
print(x)

In [ ]:
# x has shape (2, 3). 
# Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the following array:

print(x * 2)

In [ ]:
### قراءة ملف
np.loadtxt("myfile.txt")
np.genfromtxt("my_file.csv", delimiter=',')
np.savetxt("myarray.txt", a, delimiter=" ")